development:
  adapter: mysql2
  encoding: utf8
  database: cheap_eats
  username: root
  password:
  pool: 5
  timeout: 5000

test:
  adapter: mysql2
  database: cheap_eats_test
  username: root
  password:
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  database: cheap_eats
  username: root
  password:
  pool: 5
  timeout: 5000
