development:
  adapter: postgresql
  database: cheap_eats
  username: jmacwilliam
  password:
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: cheap_eats_test
  username: jmacwilliam
  password:
  pool: 5
  timeout: 5000
