development:
  adapter: postgresql
  database: cheap_eats
  username: jmacwilliam
  password:
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: cheap_eats_test
  username: jmacwilliam
  password:
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  port: <% ENV['db_port'] %>
  host: <% ENV['db_host'] %>
  database: <% ENV['db'] %>
  username: <% ENV['db_username'] %>
  password: <% ENV['db_password'] %>
  pool: 5
  timeout: 5000
